#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "Installing dependencies..."
npm install

echo "Building..."
npm run build

NODE_PATH=$(which node)
SCRIPT_PATH="$SCRIPT_DIR/dist/index.js"

echo ""
echo "✓ rails-console-mcp built successfully"
echo ""
echo "================================================================================"
echo "SETUP INSTRUCTIONS"
echo "================================================================================"
echo ""
echo "1. LOCAL (Docker) - for development with docker-compose:"
echo ""
echo "   claude mcp add rails-console -s user \\"
echo "     -e RAILS_MCP_CONTAINER=your-container-name \\"
echo "     -- $NODE_PATH $SCRIPT_PATH"
echo ""
echo "   Replace 'your-container-name' with your Docker container (e.g., 'web')."
echo "   Find it with: docker ps --format '{{.Names}}'"
echo ""
echo "--------------------------------------------------------------------------------"
echo ""
echo "2. STAGING (Kubectl) - for staging environment via Teleport:"
echo ""
echo "   First, login to Teleport and find your cluster:"
echo "     tsh login --proxy=teleport.example.com:443 teleport.example.com"
echo "     tsh kube ls"
echo "     tsh kube login your-staging-cluster"
echo ""
echo "   Then find the context name:"
echo "     kubectl config get-contexts -o name | grep staging"
echo ""
echo "   Then add the MCP server:"
echo ""
echo "   claude mcp add rails-console-staging -s user \\"
echo "     -e RAILS_MCP_MODE=kubectl \\"
echo "     -e RAILS_MCP_KUBE_CONTEXT=your-kube-context \\"
echo "     -e RAILS_MCP_KUBE_NAMESPACE=your-namespace \\"
echo "     -e RAILS_MCP_KUBE_SELECTOR=app=your-console-app \\"
echo "     -e RAILS_MCP_KUBE_CONTAINER=console \\"
echo "     -- $NODE_PATH $SCRIPT_PATH"
echo ""
echo "================================================================================"
echo ""
echo "After adding, restart Claude Code to connect."
echo ""
echo "Environment variables reference:"
echo "  RAILS_MCP_MODE            - 'docker' (default) or 'kubectl'"
echo "  RAILS_MCP_CONTAINER       - Docker container name (docker mode)"
echo "  RAILS_MCP_KUBE_CONTEXT    - Kubectl context (kubectl mode)"
echo "  RAILS_MCP_KUBE_NAMESPACE  - Kubernetes namespace (default: persona-web)"
echo "  RAILS_MCP_KUBE_SELECTOR   - Pod selector (default: app=persona-web-console)"
echo "  RAILS_MCP_KUBE_CONTAINER  - Container name (default: console)"
echo "  RAILS_MCP_COMMAND_TIMEOUT - Command timeout in ms (default: 60000)"
echo ""
